spring:
  application:
    name: data-logger-service
  redis:
    host: localhost
    port: 6379
    # password: your-password-if-needed

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
