# Redis конфигурация
redis.host=localhost
redis.port=6379
redis.password=
redis.channel.activity=logger:activity
redis.channel.error=logger:error

# Настройки логирования
logger.file.enabled=true
logger.file.path=logs
logger.file.rotation=daily
logger.console.level=INFO

# API настройки
api.host=0.0.0.0
api.port=8095
